steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/build-8.0.0', '--build-arg=PHP_IMAGE=php:8.0.0-buster', '.' ]
  waitFor: ['-']
  id: 'build-8.0.0'

- name: 'gcr.io/cloud-builders/docker'
  args: ['run', 'gcr.io/$PROJECT_ID/build-8.0.0']
  waitFor: ['build-8.0.0']
  id: 'run-8.0.0'
images: [

 'gcr.io/$PROJECT_ID/build-8.0.0'
]
